const imgUrl1 =
  "https://fotosimoveis.blob.core.windows.net/fotos-imoveis/16/360/943332/5dc92074-7-20221215_084540.jpg";

export const properties = [
  {
    id: 1,
    titulo: "Linda Casa",
    descricao:
      "Este imóvel, localizado no agradável bairro São Judas, combina a paz e a tranquilidade do ambiente com a vantagem da proximidade ao centro da cidade. Desfrute da serenidade deste bairro, enquanto permanece a poucos minutos de todas as comodidades e atrações urbanas",
    tamanho: 380,
    quartos: 3,
    banheiros: 2,
    preco: 200,
    cidade: "Guarapari",
    bairro: "São Judas Tadeu",
    vagas_garagem: 2,
    tipo: "casa",
    imgUrls: [
      "/assets/propiedade2/img1.jpg",
      "/assets/propiedade2/img2.jpg",
      "/assets/propiedade2/img3.jpg",
      "/assets/propiedade2/img4.jpg",
      "/assets/propiedade2/img5.jpg",
      "/assets/propiedade2/img6.jpg",
    ],
  },
  {
    id: 2,
    titulo: "Apartamento de frente para o mar",
    descricao:
      "Este apartamento à beira-mar oferece vistas deslumbrantes do oceano e acesso direto à praia.",
    quartos: 1,
    banheiros: 1,
    tamanho: 380,
    preco: 200,
    cidade: "Guarapari",
    bairro: "Ipiranga",
    vagas_garagem: 2,
    tipo: "apartamento",
    imgUrls: [
      "/assets/propiedade1/quarto.jpg",
      "/assets/propiedade1/salatv.jpg",
      "/assets/propiedade1/cozinha.jpg",
      "/assets/propiedade1/cozinha2.jpg",
    ],
  },
  {
    id: 3,
    titulo: "Kit Net",
    descricao:
      "Kitnet charmosa com varanda no centro da cidade, a poucos passos da praia. Perfeita para solteiros ou casais que buscam praticidade e vistas encantadoras.",
    tamanho: 380,
    quartos: 1,
    banheiros: 1,
    preco: 200,
    cidade: "Guarapari",
    bairro: "centro",
    vagas_garagem: 0,
    tipo: "apartamento",
    imgUrls: [
      "/assets/propiedade-4/img1.jpg",
      "/assets/propiedade-4/img2.jpg",
      "/assets/propiedade-4/img3.jpg",
      "/assets/propiedade-4/img4.jpg",
      "/assets/propiedade-4/img5.jpg",
      "/assets/propiedade-4/img6.jpg",
      "/assets/propiedade-4/img7.jpg",
      "/assets/propiedade-4/img8.jpg",
      "/assets/propiedade-4/img9.jpg",
      "/assets/propiedade-4/img10.jpg",
    ],
  },
  {
    id: 4,
    titulo: "Apartamento",
    descricao:
      "Apartamento próximo a todas as praias do Centro de Guarapari e comércios e pontos turisticos",
    tamanho: 380,
    quartos: 2,
    banheiros: 1,
    preco: 200,
    cidade: "Guarapari",
    bairro: "Ipiranga",
    vagas_garagem: 2,
    tipo: "apartamento",
    imgUrls: [
      "/assets/propiedade-3/img1.jpg",
      "/assets/propiedade-3/img2.jpg",
      "/assets/propiedade-3/img3.jpg",
      "/assets/propiedade-3/img4.jpg",
      "/assets/propiedade-3/img5.jpg",
      "/assets/propiedade-3/img6.jpg",
      "/assets/propiedade-3/img7.jpg",
      "/assets/propiedade-3/img8.jpg",
    ],
  },
  {
    id: 5,
    titulo: "kit Net",
    descricao:
      "Kitnet mobiliada no coração da cidade! Este espaço encantador oferece conveniência e conforto em um só lugar. Com uma decoração elegante e todos os móveis necessários, você encontrará o equilíbrio perfeito entre praticidade e estilo.",
    tamanho: 380,
    quartos: 1,
    banheiros: 1,
    preco: 200,
    cidade: "Guarapari",
    bairro: "Ipiranga",
    vagas_garagem: 2,
    tipo: "apartamento",
    imgUrls: [
      "/assets/propiedade-5/img-1.jpg",
      // "/assets/propiedade-3/img2.jpg",
      // "/assets/propiedade-3/img3.jpg",
      // "/assets/propiedade-3/img4.jpg",
      // "/assets/propiedade-3/img5.jpg",
      // "/assets/propiedade-3/img6.jpg",
      // "/assets/propiedade-3/img7.jpg",
      // "/assets/propiedade-3/img8.jpg",
    ],
  },
];
